<?php

return [
    'permission_list' => [
        [
            "id"           => "1",
            "parent_id"    => "0",
            "name"         => "Api:setting",
            "display_name" => "设置",
            "display_desc" => "",
            "url"          => "/setting",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "setting",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "2",
            "parent_id"    => "1",
            "name"         => "Api:setting/user_module",
            "display_name" => "用户模块",
            "display_desc" => "",
            "url"          => "/setting/user_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "user",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "3",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/user/list-index",
            "display_name" => "用户列表",
            "display_desc" => "对后台用户进行管理",
            "url"          => "/setting/user_module/user/list",
            "component"    => "setting/user_module/user/index",
            "guard_name"   => "web",
            "icon"         => "product-list",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "4",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/user/store-store",
            "display_name" => "添加用户",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "5",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/user/update-update",
            "display_name" => "修改用户",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "6",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/user/destroy-destroy",
            "display_name" => "删除用户",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "7",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/role/list-index",
            "display_name" => "角色列表",
            "display_desc" => "对后台角色进行管理",
            "url"          => "/setting/user_module/role/list",
            "component"    => "setting/user_module/role/index",
            "guard_name"   => "web",
            "icon"         => "role",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "8",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/role/store-store",
            "display_name" => "增加角色",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "9",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/role/update-update",
            "display_name" => "修改角色",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "10",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/role/destroy-destroy",
            "display_name" => "删除角色",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "11",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/permission/list-index",
            "display_name" => "权限列表",
            "display_desc" => "对后台权限进行管理",
            "url"          => "/setting/user_module/permission/list",
            "component"    => "setting/user_module/permission/index",
            "guard_name"   => "web",
            "icon"         => "permission",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "12",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/permission/store-store",
            "display_name" => "增加权限",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "13",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/permission/update-update",
            "display_name" => "修改权限",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "14",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/permission/destroy-destroy",
            "display_name" => "删除权限",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "19",
            "parent_id"    => "1",
            "name"         => "Api:setting/monitoring_module",
            "display_name" => "系统监控",
            "display_desc" => "",
            "url"          => "/setting/monitoring_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "monitoring_module",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "20",
            "parent_id"    => "19",
            "name"         => "Api:setting/monitoring_module/serve-serve",
            "display_name" => "服务监控",
            "display_desc" => "记录系统配置信息等",
            "url"          => "/setting/monitoring_module/serve",
            "component"    => "setting/monitoring_module/serve/index",
            "guard_name"   => "web",
            "icon"         => "serve",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "21",
            "parent_id"    => "19",
            "name"         => "Api:setting/monitoring_module/crontab-list",
            "display_name" => "定时任务",
            "display_desc" => "记录系统一些定时任务",
            "url"          => "/setting/monitoring_module/crontab",
            "component"    => "setting/monitoring_module/crontab/index",
            "guard_name"   => "web",
            "icon"         => "crontab",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "22",
            "parent_id"    => "19",
            "name"         => "Api:setting/monitoring_module/crontab/store-store",
            "display_name" => "添加定时任务",
            "display_desc" => "添加定时任务项",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "23",
            "parent_id"    => "19",
            "name"         => "Api:setting/monitoring_module/crontab/update-update",
            "display_name" => "修改定时任务",
            "display_desc" => "修改定时任务项",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "24",
            "parent_id"    => "19",
            "name"         => "Api:setting/monitoring_module/crontab/change_status-changeStatus",
            "display_name" => "修改定时任务状态",
            "display_desc" => "修改定时任务状态",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "25",
            "parent_id"    => "19",
            "name"         => "Api:setting/monitoring_module/crontab/destroy-destroy",
            "display_name" => "删除定时任务",
            "display_desc" => "删除定时任务",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "26",
            "parent_id"    => "1",
            "name"         => "Api:setting/system_module",
            "display_name" => "系统管理",
            "display_desc" => "系统管理",
            "url"          => "/setting/system_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "system_module",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "4",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "27",
            "parent_id"    => "26",
            "name"         => "Api:setting/system_module/dict_type/list-index",
            "display_name" => "字典管理",
            "display_desc" => "\t系统的一些枚举",
            "url"          => "/setting/system_module/dict/list",
            "component"    => "setting/system_module/dict/index",
            "guard_name"   => "web",
            "icon"         => "dict",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "28",
            "parent_id"    => "26",
            "name"         => "Api:setting/system_module/dict_type/store-store",
            "display_name" => "添加字典",
            "display_desc" => "添加字典操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "29",
            "parent_id"    => "26",
            "name"         => "Api:setting/system_module/dict_type/update-update",
            "display_name" => "修改字典",
            "display_desc" => "修改字典操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "30",
            "parent_id"    => "26",
            "name"         => "Api:setting/system_module/dict_type/destroy-destroy",
            "display_name" => "删除字典",
            "display_desc" => "删除字典操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "31",
            "parent_id"    => "1",
            "name"         => "Api:setting/system_module/config/list-index",
            "display_name" => "参数设置",
            "display_desc" => "一些常用参数配置",
            "url"          => "/setting/system_module/config/list",
            "component"    => "setting/system_module/config/index",
            "guard_name"   => "web",
            "icon"         => "config",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "32",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/config/store-store",
            "display_name" => "添加参数",
            "display_desc" => "添加参数操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "33",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/config/update-update",
            "display_name" => "修改参数",
            "display_desc" => "修改参数操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "34",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/config/destroy-destroy",
            "display_name" => "删除参数",
            "display_desc" => "删除参数操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "35",
            "parent_id"    => "1",
            "name"         => "Api:setting/system_module/dict_data/list-index",
            "display_name" => "字典数据",
            "display_desc" => "字典数据列表",
            "url"          => "/setting/system_module/dict_data/list/:dict_id",
            "component"    => "setting/system_module/dict/data",
            "guard_name"   => "web",
            "icon"         => "dict",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "36",
            "parent_id"    => "35",
            "name"         => "Api:setting/system_module/dict_data/store-store",
            "display_name" => "添加字典数据",
            "display_desc" => "添加字典数据操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "37",
            "parent_id"    => "35",
            "name"         => "Api:setting/system_module/dict_data/update-update",
            "display_name" => "修改字典数据",
            "display_desc" => "修改字典数据操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "38",
            "parent_id"    => "35",
            "name"         => "Api:setting/system_module/dict_data/destroy-destroy",
            "display_name" => "删除字典数据",
            "display_desc" => "删除字典数据操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "39",
            "parent_id"    => "1",
            "name"         => "Api:setting/system_module/notice/list-index",
            "display_name" => "通知管理",
            "display_desc" => "系统的一些广播通知",
            "url"          => "/setting/system_module/notice",
            "component"    => "setting/system_module/notice",
            "guard_name"   => "web",
            "icon"         => "notice",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "40",
            "parent_id"    => "39",
            "name"         => "Api:setting/system_module/notice/store-store",
            "display_name" => "添加通知",
            "display_desc" => "添加通知操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "41",
            "parent_id"    => "39",
            "name"         => "Api:setting/system_module/notice/update-update",
            "display_name" => "修改通知",
            "display_desc" => "修改通知操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "42",
            "parent_id"    => "39",
            "name"         => "Api:setting/system_module/notice/destroy-destroy",
            "display_name" => "删除通知",
            "display_desc" => "删除通知操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "43",
            "parent_id"    => "1",
            "name"         => "Api:setting/log_module",
            "display_name" => "日志管理",
            "display_desc" => "对系统一些日历进行管理",
            "url"          => "/setting/log_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "log",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "5",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "44",
            "parent_id"    => "43",
            "name"         => "Api:setting/log_module/operate_log/list-index",
            "display_name" => "操作日志",
            "display_desc" => "记录用户的一些行为",
            "url"          => "/setting/log_module/operate_log/list",
            "component"    => "setting/log_module/operateLog",
            "guard_name"   => "web",
            "icon"         => "operateLog",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "45",
            "parent_id"    => "43",
            "name"         => "Api:setting/system_module/login_log/list-index",
            "display_name" => "登陆日志",
            "display_desc" => "记录着用户登陆日志信息",
            "url"          => "/setting/log_module/login_log/list",
            "component"    => "setting/log_module/loginLog\t",
            "guard_name"   => "web",
            "icon"         => "loginLog",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "46",
            "parent_id"    => "43",
            "name"         => "setting/log_module/system_log-getLogPath",
            "display_name" => "系统日志",
            "display_desc" => "系统的框架日志以及错误日志",
            "url"          => "/setting/log_module/system_log/list",
            "component"    => "setting/log_module/systemLog",
            "guard_name"   => "web",
            "icon"         => "logs",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "47",
            "parent_id"    => "46",
            "name"         => "setting/log_module/system_log/destroy_log-deleteLog",
            "display_name" => "删除系统日志",
            "display_desc" => "删除系统日志操作",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "48",
            "parent_id"    => "1",
            "name"         => "Api:setting/technique_module",
            "display_name" => "技术支持",
            "display_desc" => "技术工具",
            "url"          => "/setting/technique_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "technique",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ],
        [
            "id"           => "49",
            "parent_id"    => "48",
            "name"         => "Api:setting/technique_module/form_build-formBuild",
            "display_name" => "表单构建",
            "display_desc" => "快速生成表单",
            "url"          => "/setting/technique_module/form_build",
            "component"    => "setting/technique_module/formBuild",
            "guard_name"   => "web",
            "icon"         => "form",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-06-09 00:00:00",
            "updated_at"   => "2021-06-09 00:00:00"
        ]
    ]
];