<?php

return [
    'permission_list' => [
        [
            "id"           => "1",
            "parent_id"    => "0",
            "name"         => "Api:setting",
            "display_name" => "设置",
            "display_desc" => "",
            "url"          => "/setting",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "group_setting",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "2",
            "parent_id"    => "1",
            "name"         => "Api:setting/user_module",
            "display_name" => "用户模块",
            "display_desc" => "",
            "url"          => "/setting/user_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "user",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "3",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/user",
            "display_name" => "用户管理",
            "display_desc" => "对后台用户进行管理",
            "url"          => "/setting/user_module/user/list",
            "component"    => "setting/user_module/user/index",
            "guard_name"   => "web",
            "icon"         => "product-list",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "4",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/list-index",
            "display_name" => "用户查询",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "5",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/store-store",
            "display_name" => "用户添加",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "6",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/update-update",
            "display_name" => "用户修改",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "7",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/destroy-destroy",
            "display_name" => "用户删除",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "8",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/change_status-changeStatus",
            "display_name" => "修改用户状态",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "9",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/permission/accord_user_permission-accordUserPermission",
            "display_name" => "分配用户功能权限",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "10",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/reset_password-resetPassword",
            "display_name" => "重置用户密码",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "11",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/role",
            "display_name" => "角色管理",
            "display_desc" => "对后台角色进行管理",
            "url"          => "/setting/user_module/role/list",
            "component"    => "setting/user_module/role/index",
            "guard_name"   => "web",
            "icon"         => "role",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "12",
            "parent_id"    => "11",
            "name"         => "Api:setting/user_module/role/list-index",
            "display_name" => "角色查询",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "13",
            "parent_id"    => "11",
            "name"         => "Api:setting/user_module/role/store-store",
            "display_name" => "角色添加",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "14",
            "parent_id"    => "11",
            "name"         => "Api:setting/user_module/role/update-update",
            "display_name" => "角色修改",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "15",
            "parent_id"    => "11",
            "name"         => "Api:setting/user_module/role/destroy-destroy",
            "display_name" => "角色删除",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "16",
            "parent_id"    => "11",
            "name"         => "Api:setting/user_module/permission/accord_role_permission-accordRolePermission",
            "display_name" => "分配角色权限",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "17",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/permission",
            "display_name" => "权限管理",
            "display_desc" => "对后台权限/菜单进行管理",
            "url"          => "/setting/user_module/permission/list",
            "component"    => "setting/user_module/permission/index",
            "guard_name"   => "web",
            "icon"         => "permission",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "18",
            "parent_id"    => "17",
            "name"         => "Api:setting/user_module/permission/list-index",
            "display_name" => "权限查询",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "19",
            "parent_id"    => "17",
            "name"         => "Api:setting/user_module/permission/store-store",
            "display_name" => "权限添加",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "20",
            "parent_id"    => "17",
            "name"         => "Api:setting/user_module/permission/update-update",
            "display_name" => "权限修改",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "21",
            "parent_id"    => "17",
            "name"         => "Api:setting/user_module/permission/destroy-destroy",
            "display_name" => "权限删除",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "22",
            "parent_id"    => "1",
            "name"         => "Api:setting/monitoring_module",
            "display_name" => "系统监控",
            "display_desc" => "",
            "url"          => "/setting/monitoring_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "monitoring_module",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "23",
            "parent_id"    => "22",
            "name"         => "Api:setting/monitoring_module/serve-serve",
            "display_name" => "服务监控",
            "display_desc" => "记录系统配置信息等",
            "url"          => "/setting/monitoring_module/serve",
            "component"    => "setting/monitoring_module/serve/index",
            "guard_name"   => "web",
            "icon"         => "serve",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "24",
            "parent_id"    => "22",
            "name"         => "Api:setting/monitoring_module/timed_task",
            "display_name" => "定时任务",
            "display_desc" => "配置系统的定时任务",
            "url"          => "/setting/monitoring_module/crontab",
            "component"    => "setting/monitoring_module/crontab/index",
            "guard_name"   => "web",
            "icon"         => "crontab",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "25",
            "parent_id"    => "24",
            "name"         => "Api:setting/monitoring_module/timed_task/list-index",
            "display_name" => "查询定时任务",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "26",
            "parent_id"    => "24",
            "name"         => "Api:setting/monitoring_module/timed_task/store-store",
            "display_name" => "添加定时任务",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "27",
            "parent_id"    => "24",
            "name"         => "Api:setting/monitoring_module/timed_task/update-update",
            "display_name" => "修改定时任务",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "28",
            "parent_id"    => "24",
            "name"         => "Api:setting/monitoring_module/timed_task/destroy-destroy",
            "display_name" => "删除定时任务",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "29",
            "parent_id"    => "24",
            "name"         => "Api:setting/monitoring_module/timed_task/change_status-changeStatus",
            "display_name" => "修改定时任务状态",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "30",
            "parent_id"    => "1",
            "name"         => "Api:setting/system_module",
            "display_name" => "系统管理",
            "display_desc" => "",
            "url"          => "/setting/system_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "system_module",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "31",
            "parent_id"    => "30",
            "name"         => "Api:setting/system_module/dict",
            "display_name" => "字典管理",
            "display_desc" => "配置系统的枚举项",
            "url"          => "/setting/system_module/dict/list",
            "component"    => "setting/system_module/dict/index",
            "guard_name"   => "web",
            "icon"         => "dict",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "32",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/dict/list-index",
            "display_name" => "字典查询",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "33",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/dict/store-store",
            "display_name" => "字典添加",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "34",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/dict/update-update",
            "display_name" => "字典修改",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "35",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/dict/destroy-destroy",
            "display_name" => "字典删除",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "36",
            "parent_id"    => "30",
            "name"         => "Api:setting/system_module/dict_data",
            "display_name" => "字典数据",
            "display_desc" => "字典数据列表",
            "url"          => "/setting/system_module/dict_data/list/:dict_id",
            "component"    => "setting/system_module/dict/data",
            "guard_name"   => "web",
            "icon"         => "dict",
            "type"         => "2",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "37",
            "parent_id"    => "36",
            "name"         => "Api:setting/system_module/dict_data/list-index",
            "display_name" => "查询字典数据",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "38",
            "parent_id"    => "36",
            "name"         => "Api:setting/system_module/dict_data/store-store",
            "display_name" => "添加字典数据",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "39",
            "parent_id"    => "36",
            "name"         => "Api:setting/system_module/dict_data/update-update",
            "display_name" => "修改字典数据",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "40",
            "parent_id"    => "36",
            "name"         => "Api:setting/system_module/dict_data/destory-destroy",
            "display_name" => "删除字典数据",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "41",
            "parent_id"    => "30",
            "name"         => "Api:setting/system_module/global_config",
            "display_name" => "参数设置",
            "display_desc" => "配置项目中一些常用的参数",
            "url"          => "/setting/system_module/global_config/config/list",
            "component"    => "setting/system_module/globalConfig/index",
            "guard_name"   => "web",
            "icon"         => "config",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "42",
            "parent_id"    => "41",
            "name"         => "Api:setting/system_module/global_config/list-index",
            "display_name" => "参数查询",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "43",
            "parent_id"    => "41",
            "name"         => "Api:setting/system_module/global_config/store-store",
            "display_name" => "添加参数",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "44",
            "parent_id"    => "41",
            "name"         => "Api:setting/system_module/global_config/update-update",
            "display_name" => "修改参数",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "45",
            "parent_id"    => "41",
            "name"         => "Api:setting/system_module/global_config/destroy-destroy",
            "display_name" => "删除参数",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "46",
            "parent_id"    => "30",
            "name"         => "Api:setting/system_module/notice",
            "display_name" => "通知管理",
            "display_desc" => "系统的一些广播通知",
            "url"          => "/setting/system_module/notice",
            "component"    => "setting/system_module/notice",
            "guard_name"   => "web",
            "icon"         => "notice",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "47",
            "parent_id"    => "46",
            "name"         => "Api:setting/system_module/notice/list-index",
            "display_name" => "通知查询",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "48",
            "parent_id"    => "46",
            "name"         => "Api:setting/system_module/notice/store-store",
            "display_name" => "添加通知",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "49",
            "parent_id"    => "46",
            "name"         => "Api:setting/system_module/notice/update-update",
            "display_name" => "修改通知",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "50",
            "parent_id"    => "46",
            "name"         => "Api:setting/system_module/notice/destroy-destroy",
            "display_name" => "删除通知",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "51",
            "parent_id"    => "30",
            "name"         => "Api:setting/system_module/advice",
            "display_name" => "系统建议",
            "display_desc" => "提供给用户反馈bug以及优化需求",
            "url"          => "/setting/system_module/advice",
            "component"    => "setting/system_module/advice",
            "guard_name"   => "web",
            "icon"         => "form",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "4",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "52",
            "parent_id"    => "51",
            "name"         => "Api:setting/system_module/advice/list-index",
            "display_name" => "系统建议查询",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "53",
            "parent_id"    => "51",
            "name"         => "Api:setting/system_module/advice/store-store",
            "display_name" => "添加系统建议",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "54",
            "parent_id"    => "51",
            "name"         => "Api:setting/system_module/advice/update-update",
            "display_name" => "修改系统建议",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "55",
            "parent_id"    => "51",
            "name"         => "Api:setting/system_module/advice/destroy-destroy",
            "display_name" => "删除系统建议",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "56",
            "parent_id"    => "51",
            "name"         => "Api:setting/system_module/advice/reply-reply",
            "display_name" => "回复系统建议",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "57",
            "parent_id"    => "1",
            "name"         => "Api:setting/log_module",
            "display_name" => "日志管理",
            "display_desc" => "",
            "url"          => "/setting/log_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "log",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "4",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "58",
            "parent_id"    => "57",
            "name"         => "Api:setting/log_module/operate_log/list-index",
            "display_name" => "操作日志",
            "display_desc" => "记录用户的一些行为日志",
            "url"          => "/setting/log_module/operate_log/list",
            "component"    => "setting/log_module/operateLog",
            "guard_name"   => "web",
            "icon"         => "operateLog",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "59",
            "parent_id"    => "57",
            "name"         => "Api:setting/log_module/login_log/list-index",
            "display_name" => "登陆日志",
            "display_desc" => "记录用户登陆信息",
            "url"          => "/setting/log_module/login_log/list",
            "component"    => "setting/log_module/loginLog",
            "guard_name"   => "web",
            "icon"         => "loginLog",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "60",
            "parent_id"    => "57",
            "name"         => "Api:setting/log_module/system_log",
            "display_name" => "系统日志",
            "display_desc" => "系统的框架日志以及错误日志",
            "url"          => "/setting/log_module/system_log/list",
            "component"    => "setting/log+module/systemLog",
            "guard_name"   => "web",
            "icon"         => "logs",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "61",
            "parent_id"    => "60",
            "name"         => "Api:setting/log_module/system_log/log_path-getLogPath",
            "display_name" => "查询系统日志",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "62",
            "parent_id"    => "60",
            "name"         => "Api:setting/log_module/system_log/destroy_log-deleteLog",
            "display_name" => "删除系统日志",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "63",
            "parent_id"    => "1",
            "name"         => "Api:setting/technique_module",
            "display_name" => "技术支持",
            "display_desc" => "",
            "url"          => "/setting/technique_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "technique",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "5",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "64",
            "parent_id"    => "63",
            "name"         => "Api:setting/technique_module/form_build-formBuild",
            "display_name" => "表单构建",
            "display_desc" => "快速生成表单",
            "url"          => "/setting/technique_module/form_build",
            "component"    => "setting/technique_module/formBuild",
            "guard_name"   => "web",
            "icon"         => "form",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "65",
            "parent_id"    => "63",
            "name"         => "Api:setting/technique_module/json_decode-jsonDecode",
            "display_name" => "Json解析",
            "display_desc" => "用来解析json表达式",
            "url"          => "/setting/technique_module/json_decode",
            "component"    => "setting/technique_module/jsonDecode",
            "guard_name"   => "web",
            "icon"         => "jsonDecode",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "66",
            "parent_id"    => "0",
            "name"         => "Api:blog",
            "display_name" => "博客",
            "display_desc" => "",
            "url"          => "/blog",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "blog",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "67",
            "parent_id"    => "66",
            "name"         => "Api:blog/picture_module",
            "display_name" => "图床模块",
            "display_desc" => "相册网站的图片资源",
            "url"          => "/blog/picture_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "pictureBed",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "68",
            "parent_id"    => "67",
            "name"         => "Api:blog/picture_module/album",
            "display_name" => "相册管理",
            "display_desc" => "相册模块管理",
            "url"          => "/blog/picture_module/album",
            "component"    => "blog/picture_module/album",
            "guard_name"   => "web",
            "icon"         => "album",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "69",
            "parent_id"    => "68",
            "name"         => "Api:blog/picture_module/album/list-index",
            "display_name" => "查询相册",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "70",
            "parent_id"    => "68",
            "name"         => "Api:blog/picture_module/album/store-store",
            "display_name" => "添加相册",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "71",
            "parent_id"    => "68",
            "name"         => "Api:blog/picture_module/album/update-update",
            "display_name" => "修改相册",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "72",
            "parent_id"    => "68",
            "name"         => "Api:blog/picture_module/album/destroy-destroy",
            "display_name" => "删除相册",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "73",
            "parent_id"    => "67",
            "name"         => "Api:blog/picture_module/photo",
            "display_name" => "图片模块",
            "display_desc" => "图片管理模块",
            "url"          => "/blog/picture_module/photo",
            "component"    => "blog/picture_module/photo",
            "guard_name"   => "web",
            "icon"         => "image",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "74",
            "parent_id"    => "73",
            "name"         => "Api:blog/picture_module/photo/list-index",
            "display_name" => "查询图片",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "75",
            "parent_id"    => "73",
            "name"         => "Api:blog/picture_module/photo/destroy-destroy",
            "display_name" => "删除图片",
            "display_desc" => "删除图片模块",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ]
    ]
];